name: Server Tests

on:
  push:
    paths-ignore:
      - '**.css'
      - '**.md'
      - '**.html'
      - '**.csv'
  
  pull_request:
    paths-ignore:
      - '**.css'
      - '**.md'
      - '**.html'
      - '**.csv'

jobs:
  tests:
    runs-on: ubuntu-18.04
    timeout-minutes: 20

    strategy:
      fail-fast: false

      matrix:
        container: [1, 2, 3]

    name: Python Unit Tests

    services:
      mysql:
        image: mariadb:10.3
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: YES
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true

      - name: Add to Hosts
        run: echo "127.0.0.1 test_site" | sudo tee -a /etc/hosts

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/*requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install
        run: |
          bash ${GITHUB_WORKSPACE}/.github/helper/install.sh
          cd ~/frappe-bench/ && source env/bin/activate
          cd apps/india_compliance && pip install -r dev-requirements.txt
        env:
          BRANCH: version-14-beta

      - name: Run Tests
        run: cd ~/frappe-bench/ && bench --site test_site run-tests --app india_compliance --coverage
        env:
          TYPE: server

      - name: Upload coverage data
        uses: actions/upload-artifact@v3
        with:
          name: coverage-${{ matrix.container }}
          path: /home/runner/frappe-bench/sites/coverage.xml

  coverage:
    name: Coverage Wrap Up
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Upload coverage data
        uses: codecov/codecov-action@v2
        with:
          name: MariaDB
          fail_ci_if_error: true
          verbose: true